Repository sortedcord/udemyscraper, pull requests merged in 2021-08, with the labels that each got.

#6 :book: Created CODE OF CONDUCT
  CODE_OF_CONDUCT.md
Labels: documentation

#12 Fetch Course 💲
  README.md
  udemyscraper.py
Labels: enhancement

#15 Implementation of Command Line Arguments
  README.md
  help.txt
  main.py
  requirements.txt
  udemyscraper.py
Labels: enhancement

#16 🌐 Added browser selection argument
  README.md
  geckodriver.exe
  help.txt
  main.py
  requirements.txt
  udemyscraper.py
  warning.txt
Labels: enhancement, optimization

#10 Switch to browser explicit wait
  udemyscraper.py
Labels: bug, optimization

#22 Options dictionary instead of multiple variables
  main.py
  texts/help.txt
  udemyscraper.py
Labels: optimization

#24 Debug Logging
  README.md
  main.py
  texts/help.txt
  udemyscraper.py
Labels: enhancement

#25 Added Lesson Details
  README.md
  texts/help.txt
  udemyscraper.py
Labels: enhancement

#27 Added Exception Handling if driver not found
  src/udemyscraper/texts/help.txt
  src/udemyscraper/texts/warning.txt
  src/udemyscraper/udemyscraper.py
Labels: bug

#29 Show Progress Bar
  README.md
  docs/command.svg
  src/udemyscraper/udemyscraper.py
Labels: enhancement, area: script

#32 🔁Added cache functionality
  .gitignore
  README.md
  src/udemyscraper/udemyscraper.py
Labels: optimization, area: module

#35 🌐 Support for Chromium based browsers
  CHANGELOG.md
  setup.py
  udemyscraper/__init__.py
  udemyscraper/udscraperscript.py
  udemyscraper/utils.py
Labels: enhancement, area: module

#21 Serialize to xml
  .gitignore
  setup.py
  udemyscraper/export/__init__.py
  udemyscraper/export/xml.py
Labels: enhancement, area: module

#34 🌐Distribution Update 0.8.0
  .gitignore
  CHANGELOG.md
  LICENSE.txt
  MANIFEST.in
  README.md
  docs/csv.gif
  docs/xml.svg
  pyproject.toml
  requirements.txt
  setup.cfg
  setup.py
  src/udemyscraper/__init__.py
  src/udemyscraper/udemyscraper.py
  udemyscraper/__init__.py
  udemyscraper/export/__init__.py
  udemyscraper/export/csv.py
  udemyscraper/export/dict.py
  udemyscraper/export/json.py
  udemyscraper/export/print.py
  udemyscraper/export/xml.py
  udemyscraper/metadata.py
  udemyscraper/udscraperscript.py
  udemyscraper/utils.py
Labels: documentation, enhancement, optimization, area: script, area: module
